
services:
  client:
    build:
      dockerfile: dockerfile.prod
    environment:
      NODE_ENV: production

  server:
    build:
      dockerfile: dockerfile.prod
    environment:
      NODE_ENV: production