services:
  client:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - ./client:/usr/src/client
      - /user/src/client/node_modules
    environment:
      - NODE_env=development
    ports:
      - '5173:5173'

  server:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - ./server:/usr/src/server
      - /user/src/server/node_modules
    environment:
      - NODE_env=development