version: '3.9'

services:
  client:
    build:
      context: ./client
    environment:
      - SERVER_HOST=server
  server:
    build:
      context: ./server
    ports:
      -'5000:5000'
    env_file:
      - ./server/.env