services:
  client:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - ./client
      - ./client/node_modules
    environment:
      - NODE_env=development
    ports:
      - '5173:5173'

  server:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - ./server
      - ./server/node_modules
    environment:
      - NODE_env=development